---
title: "tidyverse_practice"
author: "Julin Maloof"
date: "2023-07-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```
## Load and filter the dat

```{r}
dat <- read_csv("../input/UCD_garden_size_measurements_20221128_corrected.csv")

dat <- read_csv("../input/UCD_garden_size_measurements_20221128_corrected2.csv")

```

```{r}
dat <- read_csv("../input/UCD_garden_size_measurements_20221128_corrected2.csv")
```

```{r}
summary(dat)
```

```{r}
head(dat, 90)
tail(dat, 8)
```

```{r}
dat
```


```{r}
dat <- dat %>% filter(`germinated?` == 1)
summary(dat)
```
## Summaries

By pop:

```{r}
dat %>% 
  group_by(parent.pop) %>%
  summarize(Height=mean(`Height (cm)`, na.rm=TRUE), Longest_leaf=mean(`Longest leaf (cm)`, na.rm = TRUE)) %>%
  arrange(Height)
```

By pop and mf:
```{r}
dat %>% 
  group_by(parent.pop, mf) %>%
  summarize(Height=mean(`Height (cm)`, na.rm=TRUE), Longest_leaf=mean(`Longest leaf (cm)`, na.rm = TRUE)) %>%
  arrange(Height)
```

## Plotting

First let's rename the columns

```{r}
dat <- dat %>%
  rename(height_cm=`Height (cm)`, longest_leaf_cm=`Longest leaf (cm)`)
```

histogram
```{r}
dat %>%
  ggplot(aes(x=longest_leaf_cm)) +
  geom_histogram(fill="skyblue")
```

```{r}
dat %>%
  ggplot(aes(x=height_cm)) +
  geom_histogram(fill="red") 
```

```{r}
dat %>%
  ggplot(aes(x=height_cm)) +
  geom_histogram(fill="red") +
  scale_x_sqrt()
```

Relationship between length and height:

```{r}
dat %>%
  ggplot(aes(x=longest_leaf_cm, y= height_cm)) +
  geom_point()
```

```{r, fig.asp=1.5}
dat %>%
  ggplot(aes(x=longest_leaf_cm, y= height_cm)) +
  geom_point() +
  facet_wrap(~ parent.pop)
```

plot per pop:

```{r}
dat %>%
  ggplot(aes(x=parent.pop, y=longest_leaf_cm)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 33, hjust=.8,vjust=1))

```




```{r}
dat %>%
  mutate(parent.pop = fct_reorder(parent.pop, longest_leaf_cm, .desc = TRUE)) %>%
  ggplot(aes(x=parent.pop, y=longest_leaf_cm)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust=1, vjust=.5))
```

```{r}
dat %>%
  mutate(parent.pop = fct_reorder(parent.pop, height_cm)) %>%
  ggplot(aes(x=parent.pop, y=height_cm)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust=1, vjust=.5))
```

Traditional bar plot

First create a new function for sem
```{r}
sem <- function(x, na.rm=FALSE) {
  sd(x, na.rm = na.rm) / sqrt(length(na.omit(x)))
}
```

```{r}
dat.summary <- dat %>% 
  group_by(parent.pop) %>%
  summarize(Height=mean(height_cm, na.rm=TRUE), 
            sem_height=sem(height_cm, na.rm=TRUE),
            Longest_leaf=mean(longest_leaf_cm, na.rm = TRUE),
            sem_leaf=sem(longest_leaf_cm, na.rm = TRUE)) %>%
  arrange(Height)

dat.summary
```

```{r}
dat.summary %>%
  mutate(parent.pop=fct_reorder(parent.pop, Longest_leaf)) %>%
  ggplot(aes(x=parent.pop, y=Longest_leaf, ymin=Longest_leaf - sem_leaf, ymax= Longest_leaf + sem_leaf)) +
  geom_col(fill="skyblue") +
  geom_errorbar(width=.5)
```

```{r}
dat.summary %>%
  mutate(parent.pop=fct_reorder(parent.pop, Height)) %>%
  ggplot(aes(x=parent.pop, y=Height, ymin=Height-sem_height, ymax=Height+sem_height)) +
  geom_col(fill="red") +
  geom_errorbar(width=.5)
```

## simple anova

one-way
```{r}
aov1 <- aov(longest_leaf_cm ~ parent.pop, data = dat)
summary(aov1)
```
nested
```{r}
aov2 <- aov(longest_leaf_cm ~ parent.pop/mf, data = dat)
summary(aov2)
```

```{r}
library(lmerTest)
lmer1 <- lmer(longest_leaf_cm ~ (1|parent.pop/mf), data=dat)
ranova(lmer1)
```


```{r}
VarCorr(lmer1) %>% print(comp="Variance")
```

```{r}
lmer2 <- lmer(height_cm ~ (1|parent.pop/mf), data=dat)
ranova(lmer2)
```


```{r}
VarCorr(lmer2) %>%
  as.data.frame() %>%
  mutate(var.pct = vcov/sum(vcov)*100)
```

```{r}
test <- aov(height_cm ~ parent.pop, data = dat)
summary(test)
```

```{r}
test1 <- lmer(height_cm ~ (1|parent.pop), data=dat)
VarCorr(test1) %>%
  as.data.frame() %>%
  mutate(var.pct = vcov/sum(vcov)*100)
```


```{r}
dat
```

```{r}
aov1 <- aov(height_cm ~ parent.pop, data=dat)
summary(aov1)
```

```{r}
aov2 <- aov(height_cm ~ parent.pop/mf, data=dat)
summary(aov2)
```


```{r}
library(lmerTest)
```

```{r}
lme1 <- lmer(height_cm ~ (1|parent.pop/mf), data=dat)
```

```{r}
summary(lme1)
```

```{r}
ranova(lme1)
```


```{r}
VarCorr(lme1) %>%
  as.data.frame() %>%
  mutate(var.pct = vcov/sum(vcov)*100)
```









































